# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73054f505728da0e071de9085a17b6aa5c369e1a9506681232ff4d3a38d9a38c4e69b903d8ea23c15f5880492e891c2ee8163cc6a7c09f8b2d75e5667cd1945b

test:
  secret_key_base: f0d6ab9f61065c08ab230f15f718f6073af5a3fdea9b740f43e7730b5a455f3f23fbce54a41f3f6806073f39c2b52d556854a5e5441dadec838eea7d1fc88603

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
